### ISSUE TITLE
AWSアカウント作成

### ISSUE THREAD

**Issue by jimako1989** [plamo-guide/plamo-guide#27]
私の思っている作業順序は次のようなものです

 - [x] ドメイン作成 #24 
 - [x] AWS アカウント作成 (this issue)

### following tasks
 - [ ] setup AWS Lambda for #18 
 - [ ] setup AWS RDS(MySQL) for #19 
 - [ ] setup AWS ECR for #20

**Comment by tanaka-hiroki1989** [comment]
アカウント作成作業を実施し、現在アカウントが有効化されるのを待っている状況です。
有効化がメールで通知され次第、共有します。

**Comment by tanaka-hiroki1989** [comment]
- [ ] Organizationを作成
- [ ] 小嶋のAWSアカウントをOrganizationに入れ、適切な権限を付与

**Comment by jimako1989** [comment]
Organizationに入れましたので，本IssueCloseでも構いませんか？

**Comment by tanaka-hiroki1989** [comment]
OKでっす
